/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package connect.four

fun main() {
    var game = ConnectFour()

    // Storage.feedByMovesPlayed(5, 3)

    Storage.feedByMovesPlayed(10000, 15)
    println(Storage.doStorageLookup(15).hashMap.size)


    // storage.addGameToStorage(game)


    // println(storage.getRandomGame(30))

    // println(storage.getHashMapFromStorage(1)[331312312]!!.second)

}
